schema_version: 1

context:
  name: starlette-exporter
  version: "0.24.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/starlette_exporter-${{ version }}.tar.gz
  sha256: c09cb9be59d3d43f69d717c0108b90858ff226f33431493033803f8b7d3dec78

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - prometheus_client
    - python >=${{ python_min }}
    - starlette

tests:
  - python:
      imports:
        - starlette_exporter
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Prometheus metrics exporter for Starlette applications.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/stephenhillier/starlette_exporter

extra:
  recipe-maintainers:
    - janjagusch
    - ivergara
