schema_version: 1

context:
  name: starlette-exporter
  version: 0.23.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/starlette_exporter-${{ version }}.tar.gz
  sha256: f80998db2d4a3462808a9bce56950046b113d3fab6ec6c20cb6de4431d974969

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
  run:
    - prometheus_client
    - python >=${{ python_min }}
    - starlette

tests:
  - python:
      imports:
        - starlette_exporter
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Prometheus metrics exporter for Starlette applications.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/stephenhillier/starlette_exporter

extra:
  recipe-maintainers:
    - janjagusch
    - ivergara
